export enum MessageType {
	ADD_BLOCKING_RULE = 0,
	REMOVE_BLOCKING_RULE = 1,
	IS_BLOCKED = 2,
	STORAGE_CHANGED = 3,
	REQUEST_SETTINGS = 4,
	SETTINGS_CHANGED = 5,
}

export enum CommunicationRole {
	SERVICE_WORKER = 0,
	CONTENT_SCRIPT = 1,
	SETTINGS = 2,
}

export enum SettingsDesign {
	DETECT = 0,
	DARK = 1,
	LICHT = 2,
}

export enum SettingsState {
	BLOCKED_CHANNELS = 0,
	BLOCKED_TITLES = 1,
	BLOCKED_NAMES = 2,
	BLOCKED_COMMENTS = 3,
	EXCLUDED_CHANNELS = 4,
	APPEARANCE = 5,
	IMPORT_EXPORT = 6,
	ABOUT = 7,
	FAQ = 8,
}
